name: Push changelog to Discord

on:
  push:
    branches:
      - main

jobs:
  send-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Read latest changelog section and send to Discord
        run: |
          # Načítaj poslednú sekciu changelogu začínajúcu na "## ["
          LAST_CHANGELOG=$(awk '
            BEGIN { found=0 }
            /^## \[/ {
              if (found) exit
              found=1
            }
            found { print }
          ' CHANGELOG.md)

          echo -e "📦 Odosielam na Discord:\n$LAST_CHANGELOG"

          # Priprav JSON payload
          PAYLOAD=$(jq -n --arg content "🛠️ **Nový update AstroMiner!**\n$LAST_CHANGELOG" '{content: $content}')

          # Pošli payload na Discord webhook
          curl -X POST -H "Content-Type: application/json" \
               -d "$PAYLOAD" \
               "$WEBHOOK_URL"
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}