name: Push changelog to Discord

on:
  push:
    branches:
      - main

jobs:
  send-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Read and send changelog
        run: |
          LAST_CHANGELOG=$(awk '/^## /{if (found) exit; found=1} found' CHANGELOG.md)
          # Formátujeme správu ako viacriadkový reťazec
          MESSAGE="🛠️ **Nový update AstroMiner!**\n\n\`\`\`\n$LAST_CHANGELOG\n\`\`\`"
          curl -X POST -H "Content-Type: application/json" \
               -d "{\"content\": \"$MESSAGE\"}" \
               "$WEBHOOK_URL"
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}